lib/gsgms_web/router.ex
defmodule GSGMSWeb.Router do
  use GSGMSWeb, :router

  import GSGMSWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GSGMSWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Authentication routes

  scope "/", GSGMSWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register", UserRegistrationController, :new
    post "/register", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/reset-password", UserResetPasswordController, :new
    post "/reset-password", UserResetPasswordController, :create
    get "/reset-password/:token", UserResetPasswordController, :edit
    put "/reset-password/:token", UserResetPasswordController, :update
  end

  scope "/", GSGMSWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", PageLive, :index

    live "/players", PlayerLive.Index, :index
    live "/players/new", PlayerLive.Index, :new
    live "/players/:id/edit", PlayerLive.Index, :edit
    live "/players/:id", PlayerLive.Show, :show
    live "/players/:id/show/edit", PlayerLive.Show, :edit

    live "/teams", TeamLive.Index, :index
    live "/teams/new", TeamLive.Index, :new
    live "/teams/:id/edit", TeamLive.Index, :edit
    live "/teams/:id", TeamLive.Show, :show
    live "/teams/:id/show/edit", TeamLive.Show, :edit

    get "/account/settings", UserSettingsController, :edit
    put "/account/settings/update_password", UserSettingsController, :update_password
    put "/account/settings/update_email", UserSettingsController, :update_email
    put "/account/settings/update_name", UserSettingsController, :update_name
    get "/account/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", GSGMSWeb do
    pipe_through [:browser]

    delete "/users/logout", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Other scopes may use custom stacks.
  # scope "/api", GSGMSWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GSGMSWeb.Telemetry
    end
  end
end

lib/gsgms_web/controllers/user_reset_password_controller.ex
defmodule GSGMSWeb.UserResetPasswordController do
  use GSGMSWeb, :controller

  alias GSGMS.Accounts

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your e-mail is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_user_password(conn.assigns.user))
  end

  # Do not login the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Accounts.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/gsgms_web/views/user_reset_password_view.ex
defmodule GSGMSWeb.UserResetPasswordView do
  use GSGMSWeb, :view
end

lib/gsgms_web/templates/user_reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, Routes.user_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Login", to: Routes.user_session_path(@conn, :new) %>
</p>

lib/gsgms_web/templates/user_reset_password/new.html.eex
<div class="max-w-md px-8 py-6 mx-auto mt-10 text-gray-800 bg-white rounded shadow">
  <div class="space-y-4">
    <h1 class="text-3xl font-bold">Forgot your password?</h1>

    <%= form_for :user, Routes.user_reset_password_path(@conn, :create), fn f -> %>
      <div class="space-y-4">
        <div>
          <%= label f, :email, class: "block font-semibold text-sm" %>
          <%= text_input f, :email, required: true, class: "form-input w-full" %>
        </div>
        <div>
          <span class="shadow-sm">
            <%=
              submit "Send instructions to reset password",
              class: "w-full py-2 text-white bg-indigo-500 shadow rounded transition-colors ease-in duration-100 hover:bg-indigo-600"
            %>
          </span>
        </div>
      </div>
    <% end %>

    <p class="text-center">
      <%=  link "Login",
        to: Routes.user_session_path(@conn, :new),
        class: "text-indigo-500 hover:text-indigo-400"
      %>
      <span class="text-gray-300"> |</span>
      <%= link "Register",
        to: Routes.user_registration_path(@conn, :new),
        class: "text-indigo-500 hover:text-indigo-400"
      %>
    </p>
  </div>
</div>