lib/gsgms_web/router.ex
defmodule GSGMSWeb.Router do
  use GSGMSWeb, :router

  import GSGMSWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GSGMSWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Authentication routes

  scope "/", GSGMSWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register", UserRegistrationController, :new
    post "/register", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/reset-password", UserResetPasswordController, :new
    post "/reset-password", UserResetPasswordController, :create
    get "/reset-password/:token", UserResetPasswordController, :edit
    put "/reset-password/:token", UserResetPasswordController, :update
  end

  scope "/", GSGMSWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", PageLive, :index

    live "/players", PlayerLive.Index, :index
    live "/players/new", PlayerLive.Index, :new
    live "/players/:id/edit", PlayerLive.Index, :edit
    live "/players/:id", PlayerLive.Show, :show
    live "/players/:id/show/edit", PlayerLive.Show, :edit

    live "/teams", TeamLive.Index, :index
    live "/teams/new", TeamLive.Index, :new
    live "/teams/:id/edit", TeamLive.Index, :edit
    live "/teams/:id", TeamLive.Show, :show
    live "/teams/:id/show/edit", TeamLive.Show, :edit

    get "/account/settings", UserSettingsController, :edit
    put "/account/settings/update_password", UserSettingsController, :update_password
    put "/account/settings/update_email", UserSettingsController, :update_email
    put "/account/settings/update_name", UserSettingsController, :update_name
    get "/account/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", GSGMSWeb do
    pipe_through [:browser]

    delete "/users/logout", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Other scopes may use custom stacks.
  # scope "/api", GSGMSWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GSGMSWeb.Telemetry
    end
  end
end

lib/gsgms_web/views/layout_view.ex
defmodule GSGMSWeb.LayoutView do
  use GSGMSWeb, :view
end

lib/gsgms_web/templates/layout/_menu.html.eex
<ul class="flex space-x-4">
<%= if @current_user do %>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Players", to: Routes.player_index_path(@conn, :index) %>
  </li>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Teams", to: Routes.team_index_path(@conn, :index) %>
  </li>
  <%# <li><%= link "Users", to: Routes.user_index_path(@conn, :index) %></li>
<% end %>
</ul>

lib/gsgms_web/templates/layout/_user_menu.html.eex
<ul class="flex space-x-4">
<%= if @current_user do %>
  <li class="px-2 py-1 text-indigo-800 bg-indigo-100 rounded shadow-sm">
    <%= @current_user.email %>
  </li>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %>
  </li>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Logout", to: Routes.user_session_path(@conn, :delete), method: :delete %>
  </li>
<% else %>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Login", to: Routes.user_session_path(@conn, :new) %>
  </li>
  <li class="px-2 py-1 rounded hover:bg-indigo-800">
    <%= link "Register", to: Routes.user_registration_path(@conn, :new) %>
  </li>
<% end %>
</ul>

lib/gsgms_web/templates/layout/app.html.eex
<main role="main" class="container mx-auto">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/gsgms_web/templates/layout/live.html.leex
<main role="main" class="container mx-auto">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/gsgms_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "GSGMS", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="bg-gray-50">
    <header class="mb-4">
      <section class="p-4 text-sm font-semibold text-white bg-indigo-700 border-b border-indigo-800">
        <nav class="container flex items-center justify-between mx-auto" role="navigation">
          <div class="flex items-center w-1/3 space-x-4">
          <a href="/">GSGMS</a>
          <%= render "_menu.html", assigns %>
          </div>
          <div class="self-end">
          <%= render "_user_menu.html", assigns %>
          </div>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>